#!/bin/sh
set -e
cd ~

# Install Homebrew
if [ ! -f $HOME/homebrew/bin/brew ]; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
  echo "Homebrew already installed."
fi

if [ ! -d ~/dotfiles ]; then
  echo "Cloning dotfiles..."
  git clone https://github.com/FuruNov/mac-dotfiles.git
else
  echo "dotfiles already cloned."
fi

# Install some software
echo "Installing some software & library..."
brew bundle -v --file=./dotfiles/Brewfile

if [ ! -d ~/.config ]; then
  echo "Creating ~/.config directory..."
  mkdir ~/.config
fi

echo "zshの設定を読み込む"
source ~/.zshrc

echo "シンボリックリンクを貼る"
echo "Symlinking dotfiles..."
sh ~/dotfiles/shell/symlink && echo "Done."
