local alert = require("hs.alert")
local doublePress = require("doublePress")
local hyper = require("hyper")
local utils = require("utils")
-- local vim = require("vim")

hs.hotkey.bind({}, 'F19', hyper.pressed, hyper.released)
hyper:bind({}, 'g', function()
    alert("Hyper Key pressed")
end)
hyper:bind({}, "r", function()
    hs.reload()
end)

doublePress.new("ctrl", function()
    alert("You double tapped " .. "ctrl" .. "!")
end)
doublePress.new("cmd")
doublePress.new("alt")
doublePress.new("shift")

hs.alert.show("Config loaded")
